let newBoard = [
    { key: 1, name: 'End' }, 
    { key: 2, name: '', invisible: true }, 
    { key: 3, name: '', invisible: true }, 
    { key: 4, name: 'Roll' },
    { key: 5, name: '', invisible: true }, 
    { key: 6, name: '', invisible: true }, 
    { key: 7, name: 'Start' },
    { key: 8, name: '' }, 
    { key: 9, name: '', invisible: true }, 
    { key: 10, name: '', invisible: true }, 
    { key: 11, name: '0' },
    { key: 12, name: '', invisible: true }, 
    { key: 13, name: '', invisible: true }, 
    { key: 14, name: '' },
    { key: 15, name: '' }, 
    { key: 16, name: '', invisible: true }, 
    { key: 17, name: '', invisible: true }, 
    { key: 18, name: '', invisible: true },
    { key: 19, name: '', invisible: true }, 
    { key: 20, name: '', invisible: true }, 
    { key: 21, name: '' },
    { key: 22, name: '' }, 
    { key: 23, name: '', invisible: true }, 
    { key: 24, name: '', invisible: true }, 
    { key: 25, name: '', invisible: true },
    { key: 26, name: '', invisible: true }, 
    { key: 27, name: '', invisible: true }, 
    { key: 28, name: '' },
    { key: 29, name: '' }, 
    { key: 30, name: '', invisible: true }, 
    { key: 31, name: '', invisible: true }, 
    { key: 32, name: '', invisible: true },
    { key: 33, name: '', invisible: true }, 
    { key: 34, name: '', invisible: true }, 
    { key: 35, name: '' },
    { key: 36, name: '' }, 
    { key: 37, name: '', invisible: true }, 
    { key: 38, name: '', invisible: true }, 
    { key: 39, name: '', invisible: true },
    { key: 40, name: '', invisible: true }, 
    { key: 41, name: '', invisible: true }, 
    { key: 42, name: '' },
    { key: 43, name: '' }, 
    { key: 44, name: '', invisible: true }, 
    { key: 45, name: '', invisible: true }, 
    { key: 46, name: '', invisible: true },
    { key: 47, name: '', invisible: true }, 
    { key: 48, name: '', invisible: true }, 
    { key: 49, name: '' },
    { key: 50, name: '' }, 
    { key: 51, name: '', invisible: true }, 
    { key: 52, name: '', invisible: true }, 
    { key: 53, name: '', invisible: true },
    { key: 54, name: '', invisible: true }, 
    { key: 55, name: '', invisible: true }, 
    { key: 56, name: '' },
    { key: 57, name: '' }, 
    { key: 58, name: '', invisible: true }, 
    { key: 59, name: '', invisible: true }, 
    { key: 60, name: '', invisible: true },
    { key: 61, name: '', invisible: true }, 
    { key: 62, name: '', invisible: true }, 
    { key: 63, name: '' },
    { key: 64, name: '' }, 
    { key: 65, name: '', invisible: true }, 
    { key: 66, name: '', invisible: true }, 
    { key: 67, name: '', invisible: true },
    { key: 68, name: '', invisible: true }, 
    { key: 69, name: '', invisible: true }, 
    { key: 70, name: '' },
    { key: 71, name: '' }, 
    { key: 72, name: '', invisible: true }, 
    { key: 73, name: '', invisible: true }, 
    { key: 74, name: '', invisible: true },
    { key: 75, name: '', invisible: true }, 
    { key: 76, name: '', invisible: true }, 
    { key: 77, name: '' },
    { key: 78, name: '' }, 
    { key: 79, name: '', invisible: true }, 
    { key: 80, name: '', invisible: true }, 
    { key: 81, name: '', invisible: true },
    { key: 82, name: '', invisible: true }, 
    { key: 83, name: '', invisible: true }, 
    { key: 84, name: '' },
    { key: 85, name: '' }, 
    { key: 86, name: '', invisible: true }, 
    { key: 87, name: '', invisible: true }, 
    { key: 88, name: '', invisible: true },
    { key: 89, name: '', invisible: true }, 
    { key: 90, name: '', invisible: true }, 
    { key: 91, name: '' },
    { key: 92, name: '' }, 
    { key: 93, name: '', invisible: true }, 
    { key: 94, name: '', invisible: true }, 
    { key: 95, name: '', invisible: true },
    { key: 96, name: '', invisible: true }, 
    { key: 97, name: '', invisible: true }, 
    { key: 98, name: '' },
    { key: 99, name: '' }, 
    { key:100, name: '', invisible: true }, 
    { key:101, name: '', invisible: true }, 
    { key:102, name: '', invisible: true },
    { key:103, name: '', invisible: true }, 
    { key:104, name: '', invisible: true }, 
    { key:105, name: '' },
    { key:106, name: '' }, 
    { key:107, name: '' }, 
    { key:108, name: '' }, 
    { key:109, name: '' },
    { key:110, name: '' }, 
    { key:111, name: '' }, 
    { key:112, name: '' },
  ];

export { newBoard };
